version: '3'
services:
  boardgames:
    image: boardgames:latest
    command: sh -c "python manage.py makemigrations && 
                    python manage.py migrate && 
                    python manage.py collectstatic --no-input && 
                    uvicorn --host 0.0.0.0 --port 8000 Site.asgi:application"
    expose:
      - 8000
    volumes:
      - ./src/Site:/usr/local/app
    container_name: boardgames

  nginx:
    image: nginxcustom:latest
    ports:
      - 8000:80
    depends_on:
      - boardgames
    volumes:
      - ./src/Site/static/:/usr/local/app/static
    container_name: nginx

  redis:
    restart: always
    image: redis:latest
    expose:
    - "6379"
    container_name: redis

