version: '3'
services:
  boardgames:
    image: boardgames:latest
    command: sh -c "python manage.py makemigrations && 
                    python manage.py migrate && 
                    python manage.py collectstatic --no-input && 
                    gunicorn Site.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - ./src/Site:/usr/local/app
    container_name: boardgames

  nginx:
    image: nginxcustom:latest
    ports:
      - 8000:80
    depends_on:
      - boardgames
    volumes:
      - ./src/Site/static/:/usr/local/app/static
    container_name: nginx

