version: '3'
services:
  boardgames:
    image: boardgames:latest
    command: sh -c "python manage.py makemigrations && 
                    python manage.py migrate && 
                    gunicorn Site.wsgi:application --bind 0.0.0.0:8001"
    expose:
      - 8001
    volumes:
      - ./src/Site:/usr/local/app
    container_name: boardgames
  nginx:
    image: nginxcustom:latest
    ports:
      - 8001:80
    depends_on:
      - boardgames
    container_name: nginx
