# Generated by Django 2.2.14 on 2020-07-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='color',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
