# Generated by Django 2.2.14 on 2020-07-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_piece_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='session',
            field=models.CharField(max_length=50),
        ),
    ]
