# Generated by Django 2.2.14 on 2020-07-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_auto_20200708_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='chess.Board'),
        ),
    ]
