# Generated by Django 3.0.8 on 2020-07-19 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_auto_20200712_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_turn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='current_turn', to='chess.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameboard', to='chess.Board'),
        ),
        migrations.CreateModel(
            name='BoardSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='chess.Board')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupant', to='chess.Piece')),
            ],
        ),
    ]
