# Generated by Django 3.0.8 on 2020-07-19 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_auto_20200719_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardsquare',
            name='occupant',
        ),
        migrations.AddField(
            model_name='boardsquare',
            name='piece',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='piece', to='chess.Piece'),
        ),
    ]
