# Generated by Django 3.0.8 on 2020-07-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0007_auto_20200719_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardsquare',
            name='piece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piece', to='chess.Piece'),
        ),
    ]
