# Generated by Django 3.0.8 on 2020-07-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0008_auto_20200719_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='session',
        ),
    ]
